<?php

class Book extends Product
{
    private $table_name = "book";
    private $weight;

    public function __construct($db) {
        parent::__construct($db);
    }

    public function all()
    {
        $sql = "SELECT * FROM products p
        INNER JOIN book b ON b.sku = p.sku";

        $statement = $this->conn->query($sql);

        $publishers = $statement->fetchAll(PDO::FETCH_ASSOC);
        return $publishers;
    }

    public function save()
    {
        parent::save();

        $sql = "INSERT INTO book (sku, weight) VALUES (:sku, :weight)";
        $stmt= $this->conn->prepare($sql);
        $stmt->execute([
            'sku' => $this->getSku(),
            'weight' => $this->getWeight(),
        ]);

        return $stmt; // TODO: Change the autogenerated stub
    }

    public function deleteBySKU()
    {
        parent::deleteBySKU();

        return $this->conn->prepare("DELETE FROM $this->table_name WHERE sku=?")->execute([$this->getSku()]); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * @param mixed $weight
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;
    }

    public function setData($data)
    {
        parent::setData($data);
        $this->weight = $data['weight'];
    }

}